# Generated by Django 4.0.2 on 2022-10-23 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cocktail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('ingredients', models.CharField(max_length=200)),
                ('image', models.URLField()),
                ('instructions', models.TextField()),
                ('glass', models.CharField(max_length=200)),
                ('is_popular', models.BooleanField()),
            ],
        ),
    ]
