# Generated by Django 4.0.2 on 2022-10-23 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails', '0003_remove_cocktail_ingredients_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='cocktail',
        ),
        migrations.AddField(
            model_name='cocktail',
            name='ingredients',
            field=models.ManyToManyField(blank=True, related_name='ingredient', to='cocktails.Ingredient'),
        ),
    ]
