# Generated by Django 4.0.2 on 2022-10-23 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails', '0004_remove_ingredient_cocktail_cocktail_ingredients'),
    ]

    operations = [
        migrations.AddField(
            model_name='cocktail',
            name='is_alcoholic',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='image',
            field=models.URLField(default=True),
            preserve_default=False,
        ),
    ]
