# Generated by Django 4.0.2 on 2022-11-02 10:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails', '0005_cocktail_is_alcoholic_ingredient_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='cocktail',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
