# Generated by Django 4.0.2 on 2022-11-09 23:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails', '0006_cocktail_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='cocktail',
            name='category',
            field=models.CharField(choices=[('AN', 'Any'), ('OR', 'Ordindary Drink'), ('CO', 'Cocktail'), ('SH', 'Shake'), ('OT', 'Other'), ('CA', 'Cocoa'), ('ST', 'Shot'), ('CE', 'Coffee Tea'), ('HO', 'Homemade Liqueur'), ('PU', 'Punch'), ('BE', 'Beer'), ('SO', 'Soft Drink')], default='AN', max_length=2),
        ),
        migrations.AlterField(
            model_name='cocktail',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='cocktail',
            name='glass',
            field=models.CharField(choices=[('AN', 'Any'), ('HI', 'Highball Glass'), ('CO', 'Cocktail Glass'), ('OL', 'Old-fashioned Glass'), ('WH', 'Whiskey Glass'), ('CH', 'Champagne Flute'), ('CL', 'Collins Glass'), ('PO', 'Pousse Cafe Glass'), ('HU', 'Hurricane Glass'), ('IR', 'Irish coffee cup'), ('PU', 'Punch Bowl'), ('PT', 'Pitcher'), ('PI', 'Pint Glass'), ('CP', 'Coupette Glass'), ('PA', 'Parfait Glass'), ('MA', 'Martini Glass'), ('BA', 'Balloon Glass'), ('CU', 'Coupe Glass')], default='AN', max_length=2),
        ),
        migrations.AlterField(
            model_name='cocktail',
            name='is_alcoholic',
            field=models.CharField(choices=[('AN', 'Any'), ('AL', 'Alcoholic'), ('NO', 'Not Alcoholic')], default='AN', max_length=2),
        ),
        migrations.AlterField(
            model_name='cocktail',
            name='is_popular',
            field=models.CharField(choices=[('AN', 'Any'), ('PO', 'Popular'), ('NO', 'Not Popular')], default='AN', max_length=2),
        ),
    ]
