# Generated by Django 4.0.2 on 2022-11-14 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails', '0007_cocktail_category_alter_cocktail_date_created_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cocktail',
            name='ingredients',
        ),
    ]
