# Generated by Django 4.0.2 on 2022-11-19 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails', '0008_remove_cocktail_ingredients'),
    ]

    operations = [
        migrations.AddField(
            model_name='cocktail',
            name='ingredients',
            field=models.ManyToManyField(blank=True, related_name='ingredient', to='cocktails.Ingredient'),
        ),
    ]
